### ISSUE TITLE
Cache is used although changes are made

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/actions#4]
https://github.com/Whist-Team/Whist-Core/runs/7483094318?check_suite_focus=true

**Comment by iTitus** [comment]
I see no error.
If there were one, poetry would re-install things.

**Comment by Segelzwerg** [comment]
> I see no error.
> If there were one, poetry would re-install things.

I double checked the file exists. Path is also correct. How could else could it be missing?

**Comment by iTitus** [comment]
You mean the test error?
I thought this issue was for a cache problem?

**Comment by iTitus** [comment]
I fixed the problem which caused the tests to fail, you just did some typos.
